version: "3.8"

services:
  angulardevapp:
    build:
      context: .
      target: Dev
    restart: always
    container_name: angulardevapp
    ports:
      - "4200:4200"
    volumes:
      - "/app/node_modules"
      - .:/app
      